macro(basic_demo_project_setup NAME)
    project(${NAME})
    set(CMAKE_CXX_STANDARD 17)
    include_directories(. src)
    include(../0_shared_code/include_all.cmake)
    add_compile_options(--include ${PROJECT_SOURCE_DIR}/../0_shared_code/src/shared/forced_includes/macros.hpp)
    set(CMAKE_SHARED_LIBRARY_PREFIX "")
    add_library(${NAME} SHARED ${SHARED_SOURCES})
    set_target_properties(${NAME} PROPERTIES OUTPUT_NAME "XInput9_1_0")
endmacro()